AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Cancun Booking API Infrastructure template
Parameters:
  MaxStayDays:
    Description: Max Stay days
    Type: String
  MaxDaysBookingAdvance:
    Description: Max Days Booking Advance
    Type: String
  MinDaysBookingAdvance:
    Description: Min Days Booking Advance
    Type: String
  StageName:
    Description: Stage name
    Type: String
    Default: Prod
  DBUsername:
    Description: Db User Name
    Type: String
  DBPassword:
    Description: Db Password
    Type: String
  DbConnectionString:
    Description: Db Connection string
    Type: String
    Default: ''

Resources:
  
  CancunBookingApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName

  PlaceReservationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Place Reservation Order
      FunctionName: !Sub "Cancun-Booking-${StageName}-PlaceReservation-Fn"
      Handler: "Cancun.Booking.PlaceReservation.Lambda::Cancun.Booking.PlaceReservation.Lambda.Function::FunctionHandler"
      CodeUri: src/
      Runtime: dotnet6
      Timeout: 4
      Events:
        ReservationOrder:
          Type: Api
          Properties:
            RestApiId: !Ref CancunBookingApiGateway
            Path: /ReservationOrder
            Method: POST
      Environment:
        Variables:
          MAXSTAYDAYS: !Ref MaxStayDays
          MAXDAYSBOOKINGADVANCE: !Ref MaxDaysBookingAdvance
          MINDAYSBOOKINGADVANCE: !Ref MinDaysBookingAdvance
          DBCONNECTIONSTRING: !Ref DbConnectionString

  CancelReservationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Cancel Reservation Order
      FunctionName: !Sub "Cancun-Booking-${StageName}-CancelReservation-Fn"
      Handler: "Cancun.Booking.CancelReservation.Lambda::Cancun.Booking.CancelReservation.Lambda.Function::FunctionHandler"
      CodeUri: src/
      Runtime: dotnet6
      Timeout: 4
      Events:
        CancelReservationOrder:
          Type: Api
          Properties:
            RestApiId: !Ref CancunBookingApiGateway
            Path: /CancelReservationOrder
            Method: POST
      Environment:
        Variables:
          MAXSTAYDAYS: !Ref MaxStayDays
          MAXDAYSBOOKINGADVANCE: !Ref MaxDaysBookingAdvance
          MINDAYSBOOKINGADVANCE: !Ref MinDaysBookingAdvance
          DBCONNECTIONSTRING: !Ref DbConnectionString

  ModifyReservationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Modify Reservation Order
      FunctionName: !Sub "Cancun-Booking-${StageName}-ModifyReservation-Fn"
      Handler: "Cancun.Booking.ModifyReservation.Lambda::Cancun.Booking.ModifyReservation.Lambda.Function::FunctionHandler"
      CodeUri: src/
      Runtime: dotnet6
      Timeout: 4
      Events:
        ModifyReservationOrder:
          Type: Api
          Properties:
            RestApiId: !Ref CancunBookingApiGateway
            Path: /ModifyReservationOrder
            Method: POST
      Environment:
        Variables:
          MAXSTAYDAYS: !Ref MaxStayDays
          MAXDAYSBOOKINGADVANCE: !Ref MaxDaysBookingAdvance
          MINDAYSBOOKINGADVANCE: !Ref MinDaysBookingAdvance
          DBCONNECTIONSTRING: !Ref DbConnectionString

  CheckRoomAvailabilityFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Check Room Availability
      FunctionName: !Sub "Cancun-Booking-${StageName}-CheckRoomAvailability-Fn"
      Handler: "Cancun.Booking.RoomAvailability.Lambda::Cancun.Booking.RoomAvailability.Lambda.Function::FunctionHandler"
      CodeUri: src/
      Runtime: dotnet6
      Timeout: 4
      Events:
        CheckRoomAvailability:
          Type: Api
          Properties:
            RestApiId: !Ref CancunBookingApiGateway
            Path: /CheckRoomAvailability
            Method: POST
      Environment:
        Variables:
          MAXSTAYDAYS: !Ref MaxStayDays
          MAXDAYSBOOKINGADVANCE: !Ref MaxDaysBookingAdvance
          MINDAYSBOOKINGADVANCE: !Ref MinDaysBookingAdvance
          DBCONNECTIONSTRING: !Ref DbConnectionString

  # VPC and network infra
  CancunVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags: 
        - Key: Name
          Value: !Sub "Cancun-${StageName}-VPC"

  CancunRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref CancunVPC

  CancunSubNetPrivateA:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs 
          Ref: 'AWS::Region'
      VpcId: !Ref CancunVPC
      CidrBlock: "10.0.0.0/24"
      Tags: 
        - Key: Name
          Value: !Sub "Cancun-subnetprivate-A-${StageName}"

  CancunSubNetPrivateB:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select 
        - 1
        - !GetAZs 
          Ref: 'AWS::Region'
      VpcId: !Ref CancunVPC
      CidrBlock: "10.0.1.0/24"
      Tags: 
        - Key: Name
          Value: !Sub "Cancun-subnetprivate-B-${StageName}"

  CancunInstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "Cancun RDS Security Group - ${StageName}"
      GroupDescription: !Sub "Cancun - RDS traffic - ${StageName}"
      VpcId: !Ref CancunVPC
      SecurityGroupEgress:
      - IpProtocol: "-1"
        CidrIp: "0.0.0.0/0"
      Tags: 
        - Key: Name
          Value: !Sub "Cancun-instance-security-group-${StageName}"

  CancunInstanceSecurityGroupIngress:
    Type: "AWS::EC2::SecurityGroupIngress"
    DependsOn: "CancunInstanceSecurityGroup"
    Properties:
      GroupId: !Ref "CancunInstanceSecurityGroup"
      IpProtocol: "tcp"
      FromPort: "3306"
      ToPort: "3306"
      SourceSecurityGroupId: !Ref "CancunInstanceSecurityGroup"

  # DATABASE

  CancunRdsSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupName: !Sub "Cancun_${StageName}_RDS_Subnet_Group"
      DBSubnetGroupDescription: "Cancun - ${StageName} - RDS Subnet Group"
      SubnetIds:
      - !Ref CancunSubNetPrivateA
      - !Ref CancunSubNetPrivateB

  CancunRDSCluster:
    Type: "AWS::RDS::DBCluster"
    Properties:
      DBSubnetGroupName: !Ref "CancunRdsSubnetGroup"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DatabaseName: "cancundb"
      Engine: "aurora"
      EngineMode: "serverless"
      VpcSecurityGroupIds:
      - !Ref "CancunInstanceSecurityGroup"
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 2
        MinCapacity: 1
        SecondsUntilAutoPause: 300