name: Main branch workflow prod
on:
  push:
    branches:
      - main

env:
  SOLUTION_PATH: "src/"
  OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  REGION: us-east-1

jobs:
  Build-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

  Deploy-Infra-Prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package
        run: |
          sam package --s3-bucket ${{ secrets.AWS_BUCKET_DEPLOY }} --template-file template.yaml --output-template-file deploy.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

      - name: Deploy
        run: |
          aws cloudformation deploy --template-file deploy.yaml --stack-name prod-cancun-booking --capabilities CAPABILITY_NAMED_IAM --parameter-overrides MaxStayDays=3 MaxDaysBookingAdvance=30 MinDaysBookingAdvance=1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
